### PR TITLE
Admin

### PR DESCRIPTION
**Pull request by alexwohlbruck**
Maybe make a new branch for Admin page development? Making changes to master scares me

### CODE REVIEW

**Comment by bnussman** [comment]
looking really good. Should I make an admin branch? 

Also, you should be able to implement the "Users" page now. Get data from GET https://ridebeep.app/v1/user to list all users.

**Comment by bnussman** [comment]
We should maybe discuss how our backend and frontend should handle pagination when it comes to listing a ton of users or reports, etc..

**Comment by alexwohlbruck** [comment]
Yes definitely plan on implementing pagination. I've just added the users table and it loads all of them.

I've started using Redux to manage the data from the API. Is that good with you or do you prefer another library for state management? I saw you're using the Context api to store logged in user data, I don't know if it is an antipattern to use Context with Redux, you're call. Maybe we can combine them.

**Comment by bnussman** [comment]
I can definitely get behind Redux. I've just been **too scared** to lean it... We can consider moving the user data to a redux store but be aware that the context is responsible for triggering re-renders when the socket updates the user data... not sure if redux can handles this the way we have it (it probably can)

**Comment by bnussman** [comment]
Thank you for the Users table, nice to finally have that without having to open up the DB's web interface!!

**Comment by alexwohlbruck** [comment]
Redux will re-render the UI when any new data is put into the store, we'll just have to have socketio talking to redux instead. If you've got time someday it'd be cool if you can walk me through how you did the websockets. 
Also, yes an admin branch that I can commit to would be cool lol.
And let me know if you add any options for searching/filtering/pagination in the API. That would make it pretty complete.

**Comment by bnussman** [comment]
I'm rolling out https://github.com/bnussman/Beep-API-v3/commit/c1c82f0f02acfdf1c30d433266b4e42077dd1abc 

This allows admins to get more detailed user info when they GET https://ridebeep.app/v1/user/{id}  for this route, authentication is obviously optional, but if user is an admin they will get all user data (except their password)

I also added PATCH https://ridebeep.app/v1/user/{id} to allow admins to edit user accounts.

**Comment by bnussman** [comment]
I'll let you know what I decide to do about pagination within the API. Expect me to be working on the API a lot over the next few days.

**Comment by bnussman** [comment]
love the relative timestamps. Good idea

**Comment by alexwohlbruck** [comment]
I added some code that uses a mapping API to lookup the origin and destination addresses and get the coordinates back to show on a map. Although we should be getting those coordinates before the entries are stored in the database. See if you can make some fields in the beeper table for coordinates.
Right now I just lookup the first 6 beeps coordinate data. Any of the others will throw an error lol.

Also, if you refresh the page while viewing a beep, the data isn't able to load. This is because we don't have an API route for a single beep, gonna need to add that also.

**Comment by alexwohlbruck** [comment]
Will work on pagination next

**Pull request merged**
